language: java
jdk:
  - oraclejdk9

sudo: required

services:
  - docker

#before_install:
#  - docker-compose up -d

script:
  - ./gradlew bootJar

after_success:
  - if [ "$TRAVIS_BRANCH" == "docker" ]; then
    docker build -t pablow91/money-dispatcher:latest .;
    docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD";
    docker push pablow91/money-dispatcher:latest;
    fi